steps:
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d build/ gs://m-ubeira-static-website-bucket

options:
  logging: NONE
timeout: 1200s
